FROM python:3.10-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y build-essential libgl1-mesa-glx

# Copy requirements and install
COPY requirements.txt .
RUN python3.12 -m venv venv && \
    . venv/bin/activate && \
    pip install --upgrade pip && \
    pip install -r requirements.txt

# Copy the full app code
COPY . .

EXPOSE 8000

CMD ["bash"]
